name: Test Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    name: Test Self Hosted Runner
    runs-on: self-hosted

    steps:
      - name: Print basic runner info
        run: |
          echo "Runner Name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Arch: $RUNNER_ARCH"
          echo "Runner Labels: $RUNNER_LABELS"
          uname -a

      - name: Ping Google
        run: |
          echo "Pinging local server..."
          ping -c 10 10.21.232.1